name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Flutter action
      uses: subosito/flutter-action@v2.23.0
    - name: Setup Python
      uses: actions/setup-python@v7.0.0
    - name: Set target for rust
      run: |
        rustup target add aarch64-linux-android
        rustup target add x86_64-linux-android
    - name: Install system deps
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
    - name: Check Rust
      run: |
        cd native
        cargo check
    - name: Prebuild
      run: python3 pre_build.py
    - name: Flutter check
      run: |
        flutter format --set-exit-if-changed
        flutter analyze
